"""empty message

Revision ID: a6e2b6178823
Revises: b4bfbf518eed
Create Date: 2018-03-06 16:17:54.599133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e2b6178823'
down_revision = 'b4bfbf518eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.Column('machine_id', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('machine_id', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('timestamp', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###
