"""empty message

Revision ID: b4bfbf518eed
Revises: 
Create Date: 2018-03-06 15:46:51.622283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bfbf518eed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.Column('machine_id', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
